package com.report.word;

import java.util.ArrayList;
import java.util.List;

public class Constant {
	public final static List<String> Patterns = new ArrayList<String>();
	static {
		//一般信息
		Patterns.add("姓名(.*)[\t]*[\r\n]*性别");
		Patterns.add("性别(.*)[\t]*[\r\n]*年龄");
		Patterns.add("年龄(.*)[\t]*[\r\n]*部门");
		Patterns.add("部门(.*)[\t]*[\r\n]*登记号");
		Patterns.add("登记号(.*)[\t]*[\r\n]*日期");
		Patterns.add("日期(.*)[\t]*[\r\n]*单位");
		Patterns.add("单位(.*)[\t]*[\r\n]*总检结论及建议");
		//总检结论及建议
		Patterns.add("总检结论及建议:([\\s\\S]*总检医生:.*[\r\n])");
		//内科检查
		Patterns.add("身高(.*)[\t]*[\r\n]*体重");
		Patterns.add("体重(.*)[\t]*[\r\n]*BMI");
		Patterns.add("BMI(.*)[\t]*[\r\n]*发育");
		Patterns.add("发育(.*)[\t]*[\r\n]*营养");
		Patterns.add("嗜好(.*)[\t]*[\r\n]*药物过敏史");
		Patterns.add("药物过敏史(.*)[\t]*[\r\n]*主要病史");
		Patterns.add("主要病史(.*)[\t]*[\r\n]*家族史");
		Patterns.add("家族史(.*)[\t]*[\r\n]*心脏");
		Patterns.add("心脏(.*)[\t]*[\r\n]*肺部检查");
		Patterns.add("肺部检查(.*)[\t]*[\r\n]*腹部");
		Patterns.add("腹部(.*)[\t]*[\r\n]*肝脏");
		Patterns.add("肝脏(.*)[\t]*[\r\n]*脾脏");
		Patterns.add("脾脏(.*)[\t]*[\r\n]*胆囊");
		Patterns.add("胆囊(.*)[\t]*[\r\n]*双肾");
		Patterns.add("双肾(.*)[\t]*[\r\n]*收缩压");
		Patterns.add("收缩压(.*)[\t]*[\r\n]*舒张压");
		Patterns.add("舒张压(.*)[\t]*[\r\n]*医生");
		//外科检查
		Patterns.add("皮肤粘膜(.*)[\t]*[\r\n]*甲状腺");
		Patterns.add("甲状腺(.*)[\t]*[\r\n]*颈部淋巴结");
		Patterns.add("颈部淋巴结(.*)[\t]*[\r\n]*颈椎");
		Patterns.add("颈椎(.*)[\t]*[\r\n]*四肢");
		Patterns.add("四肢(.*)[\t]*[\r\n]*脊柱");
		Patterns.add("脊柱(.*)[\t]*[\r\n]*四肢关节");
		Patterns.add("四肢关节(.*)[\t]*[\r\n]*医生");
		//妇科检查 没有文档 占位
		Patterns.add("本科既往史和现患疾病(.*)[\t]*[\r\n]*外阴");
		Patterns.add("外阴(.*)[\t]*[\r\n]*阴道");
		Patterns.add("阴道(.*)[\t]*[\r\n]*阴道分泌物");
		Patterns.add("阴道分泌物(.*)[\t]*[\r\n]*宫颈");
		Patterns.add("宫颈(.*)[\t]*[\r\n]*子宫体");
		Patterns.add("子宫体(.*)[\t]*[\r\n]*附件");
		Patterns.add("附件(.*)[\t]*[\r\n]*附件");
		//血型 没有文档 占位
		Patterns.add("ABO血型(.*)[\t]*[\r\n]*Rh(D)血型");
		Patterns.add("Rh(D)血型(.*)[\t]*[\r\n]*Rh(D)血型");
		//风湿检验四项 没有文档 占位
		Patterns.add("C-反应蛋白(.*)[\t]*[\r\n]*抗环瓜氨酸肽抗体");
		Patterns.add("抗环瓜氨酸肽抗体(.*)[\t]*[\r\n]*抗O");
		Patterns.add("抗O(.*)[\t]*[\r\n]*类风湿因子");
		Patterns.add("类风湿因子(.*)[\t]*[\r\n]*类风湿因子");
		//血沉 没有文档 占位
		Patterns.add("血沉(.*)[\t]*[\r\n]*红细胞沉降率测定");
		Patterns.add("红细胞沉降率测定(.*)[\t]*[\r\n]*红细胞沉降率测定");
		//胃功能 没有文档 占位
		Patterns.add("胃蛋白酶原I(.*)[\t]*[\r\n]*胃蛋白酶原II");
		Patterns.add("胃蛋白酶原II(.*)[\t]*[\r\n]*胃蛋白酶原II");
		//甲状腺功能检测
		Patterns.add("FT4[\t]{1,}([\\d.\\t]*pmol/L)[\t]{1,}");
		Patterns.add("FT3[\t]{1,}([\\d.\\t]*pmol/L)[\t]{1,}");
		Patterns.add("TSH[\t]{1,}([\\d.\\t]*uIU/mL)[\t]{1,}");
		Patterns.add("ATPO[\t]{1,}([\\d.\\t]*IU/mL)[\t]{1,}");
		Patterns.add("TG-Ab[\t]{1,}([\\d.\\t]*IU/mL)[\t]{1,}");
		//肝炎全套 没有文档 占位
		Patterns.add("甲肝抗体IgM(.*)[\t]*[\r\n]*甲肝抗体IgM");
		Patterns.add("抗丙肝IgG(.*)[\t]*[\r\n]*抗丙肝IgG");
		Patterns.add("乙肝表面抗体(.*)[\t]*[\r\n]*乙肝表面抗体");
		Patterns.add("乙肝e抗原(.*)[\t]*[\r\n]*乙肝e抗原");
		Patterns.add("乙肝e抗体(.*)[\t]*[\r\n]*乙肝e抗体");
		Patterns.add("戊肝抗体IgM(.*)[\t]*[\r\n]*戊肝抗体IgM");
		Patterns.add("乙肝核心抗体(.*)[\t]*[\r\n]*乙肝核心抗体");
		Patterns.add("(乙肝表面抗原.*)[\t]*[\r\n]*乙肝表面抗原");
		//生化全套 部分没有 占位
		Patterns.add("二氧化碳[\t]{1,}([\\d.\\t]*g/L)[\t]{1,}");
		Patterns.add("α-L-岩藻糖苷酶[\t]{1,}([\\d.\\t]*g/L)[\t]{1,}");
		Patterns.add("亮氨酸转肽酶[\t]{1,}([\\d.\\t]*g/L)[\t]{1,}");
		Patterns.add("ALB[\t]{1,}([\\d.\\t]*g/L)[\t]{1,}");
		Patterns.add("α1球蛋白[\t]{1,}([\\d.\\t]*g/L)[\t]{1,}");
		Patterns.add("α2球蛋白[\t]{1,}([\\d.\\t]*g/L)[\t]{1,}");
		Patterns.add("β球蛋白[\t]{1,}([\\d.\\t]*g/L)[\t]{1,}");
		Patterns.add("尿素氮/肌酐[\t]{1,}([\\d.\\t]*g/L)[\t]{1,}");
		Patterns.add("γ球蛋白[\t]{1,}([\\d.\\t]*g/L)[\t]{1,}");
		Patterns.add("阴离子间隙[\t]{1,}([\\d.\\t]*g/L)[\t]{1,}");
		Patterns.add("渗透压[\t]{1,}([\\d.\\t]*g/L)[\t]{1,}");
		Patterns.add("ALT[\t]{1,}([\\d.\\t]*U/L)[\t]{1,}");
		Patterns.add("AST[\t]{1,}([\\d.\\t]*U/L)[\t]{1,}");
		Patterns.add("肌酸激酶[\t]{1,}([\\d.\\t]*U/L)[\t]{1,}");
		Patterns.add("乳酸脱氢酶[\t]{1,}([\\d.\\t]*U/L)[\t]{1,}");
		Patterns.add("TP[\t]{1,}([\\d.\\t]*g/L)[\t]{1,}");
		Patterns.add("ALB[\t]{1,}([\\d.\\t]*g/L)[\t]{1,}");
		Patterns.add("GGT[\t]{1,}([\\d.\\t]*U/L)[\t]{1,}");
		Patterns.add("碱性磷酸酶[\t]{1,}([\\d.\\t]*U/L)[\t]{1,}");
		Patterns.add("总胆红素[\t]{1,}([\\d.\\t]*U/L)[\t]{1,}");
		Patterns.add("直接胆红素[\t]{1,}([\\d.\\t]*U/L)[\t]{1,}");
		Patterns.add("BUN[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("CREA[\t]{1,}([\\d.\\t]*umol/L)[\t]{1,}");
		Patterns.add("GLU[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("磷[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("T-CHO[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("Trig[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("钾[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("钠[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("氯[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("HDL-C[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("URIC[\t]{1,}([\\d.\\t]*umol/L)[\t]{1,}");
		Patterns.add("脂蛋白a[\t]{1,}([\\d.\\t]*umol/L)[\t]{1,}");
		Patterns.add("LDL-C[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("Ca[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("ALT/AST[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("球蛋白[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("白/球比[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("间接胆红素[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("腺苷脱氨酶[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("镁[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("前白蛋白[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("肌酸激酶同工酶[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("α-羟丁酸脱氢酶[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("胆碱酯酶[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		Patterns.add("果糖胺[\t]{1,}([\\d.\\t]*mmol/L)[\t]{1,}");
		//未分类
		Patterns.add("AFP[\t]{1,}([\\d.\\t]*ng/mL)[\t]{1,}");
		Patterns.add("CEA[\t]{1,}([\\d.\\t]*ng/mL)[\t]{1,}");
		Patterns.add("CA50[\t]{1,}([\\d.\\t]*IU/mL)[\t]{1,}");
		Patterns.add("CA72-4[\t]{1,}([\\d.\\t]*U/mL)[\t]{1,}");
		Patterns.add("CA19-9[\t]{1,}([\\d.\\t]*U/mL)[\t]{1,}");
		Patterns.add("CA242[\t]{1,}([\\d.\\t]*IU/mL)[\t]{1,}");
		Patterns.add("CYFRA21-1[\t]{1,}([\\d.\\t]*ng/mL)[\t]{1,}");
		Patterns.add("NSE[\t]{1,}([\\d.\\t]*ng/mL)[\t]{1,}");
		Patterns.add("I[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		//宫颈癌早期筛查 没有文档 占位
		Patterns.add("HPV6[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV11[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV42[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV43[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV81[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV16[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV18[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV31[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV33[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV35[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV39[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV45[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV51[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV52[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV53[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV56[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV58[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV59[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV66[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV68[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV73[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV82[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HPV83[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		//未分类  部分没有文档 占位
		Patterns.add("糖类抗原125[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("糖类抗原15-3[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("特异β人绒毛膜促性腺激素[\t]{1,}([\\d.\\t]*ug/L)[\t]{1,}");
		Patterns.add("HCY[\t]{1,}([\\d.\\t]*umol/L)[\t]{1,}");
		Patterns.add("胸苷激酶1[\t]{1,}([\\d.\\t]*pmol/L)[\t]{1,}");
		//酒精基因检测 没有文档 占位
		Patterns.add("ALDH2基因型检测[\t]{1,}([\\d.\\t]*pmol/L)[\t]{1,}");
		//前列腺特异性抗原检查 没有文档 占位
		Patterns.add("游离前列腺特异性抗原[\t]{1,}([\\d.\\t]*pmol/L)[\t]{1,}");
		Patterns.add("总前列腺特异性抗原[\t]{1,}([\\d.\\t]*pmol/L)[\t]{1,}");
		//血常规
		Patterns.add("WBC[\t]{1,}([\\d.\\t]*109/L)[\t]{1,}");
		Patterns.add("NEUT#[\t]{1,}([\\d.\\t]*109/L)[\t]{1,}");
		Patterns.add("MONO#[\t]{1,}([\\d.\\t]*109/L)[\t]{1,}");
		Patterns.add("LYMPH#[\t]{1,}([\\d.\\t]*109/L)[\t]{1,}");
		Patterns.add("RBC[\t]{1,}([\\d.\\t]*1012/L)[\t]{1,}");
		Patterns.add("HGB[\t]{1,}([\\d.\\t]*g/L)[\t]{1,}");
		Patterns.add("MCV[\t]{1,}([\\d.\\t]*fL)[\t]{1,}");
		Patterns.add("EO#[\t]{1,}([\\d.\\t]*109/L)[\t]{1,}");
		Patterns.add("BASO#[\t]{1,}([\\d.\\t]*109/L)[\t]{1,}");
		Patterns.add("P-LCR[\t]{1,}([\\d.\\t]*%)[\t]{1,}");
		Patterns.add("NEUT%[\t]{1,}([\\d.\\t]*%)[\t]{1,}");
		Patterns.add("LYMPH%[\t]{1,}([\\d.\\t]*%)[\t]{1,}");
		Patterns.add("MONO%[\t]{1,}([\\d.\\t]*%)[\t]{1,}");
		Patterns.add("EO%[\t]{1,}([\\d.\\t]*%)[\t]{1,}");
		Patterns.add("BASO%[\t]{1,}([\\d.\\t]*%)[\t]{1,}");
		Patterns.add("红细胞比积[\t]{1,}([\\d.\\t]*%)[\t]{1,}");
		Patterns.add("MCH[\t]{1,}([\\d.\\t]*pg)[\t]{1,}");
		Patterns.add("MCHC[\t]{1,}([\\d.\\t]*g/L)[\t]{1,}");
		Patterns.add("RDW-C[\t]{1,}([\\d.\\t]*%)[\t]{1,}");
		Patterns.add("PLT[\t]{1,}([\\d.\\t]*109/L)[\t]{1,}");
		Patterns.add("PDW[\t]{1,}([\\d.\\t]*%)[\t]{1,}");
		Patterns.add("MPV[\t]{1,}([\\d.\\t]*fL)[\t]{1,}");
		Patterns.add("PCT[\t]{1,}([\\d.\\t]*%)[\t]{1,}");
		Patterns.add("RDW-S[\t]{1,}([\\d.\\t]*fL)[\t]{1,}");
		//尿常规
		Patterns.add("VC[\t]{1,}([\\d.\\t]*fL)[\t]{1,}");
		Patterns.add("GLU[\t]{1,}([\\D]{1,}?[\t]{1,}?[\\D]{1,}?)[\r\n]{1}");
		Patterns.add("KET[\t]{1,}([\\D]{1,}?[\t]{1,}?[\\D]{1,}?)[\r\n]{1}");
		Patterns.add("BIL[\t]{1,}([\\D]{1,}?[\t]{1,}?[\\D]{1,}?)[\r\n]{1}");
		Patterns.add("PRO[\t]{1,}([\\D]{1,}?[\t]{1,}?[\\D]{1,}?)[\r\n]{1}");
		Patterns.add("NIT[\t]{1,}([\\D]{1,}?[\t]{1,}?[\\D]{1,}?)[\r\n]{1}");
		Patterns.add("PH[\t]{1,}([\\d.]*)[\t]{1,3}");
		Patterns.add("SG[\t]{1,}([\\d.]*)[\t]{1,3}");
		Patterns.add("BLD[\t]{1,}([\\D]{1,}?[\t]{1,}?[\\D]{1,}?)[\r\n]{1}");
		Patterns.add("URO[\t]{1,}([\\D]{1,}?[\t]{1,}?[\\D]{1,}?)[\r\n]{1}");
		Patterns.add("WBC[\t]{1,}([\\D]{1,}?[\t]{1,}?[\\D]{1,}?)[\r\n]{1}");
		//未分类 部分没有 占位
		Patterns.add("HbA1c\\[体检\\][\r\n]{1,}([\\s\\S]*?日期:[\\d-]*)");
		Patterns.add("乳腺彩色多普勒超声检查\\[体检\\][\r\n]{1,}([\\s\\S]*?日期:[\\d-]*)");
		Patterns.add("腋窝淋巴结彩色多普勒超声检查\\[体检\\][\r\n]{1,}([\\s\\S]*?日期:[\\d-]*)");
		Patterns.add("乳腺钼钯\\[体检\\][\r\n]{1,}([\\s\\S]*?日期:[\\d-]*)");
		Patterns.add("心脏彩色多普勒超声检查\\[体检\\][\r\n]{1,}([\\s\\S]*?日期:[\\d-]*)");
		Patterns.add("甲状腺彩色多普勒超声检查[\r\n]{1,}([\\s\\S]*?日期:[\\d-]*)");
		Patterns.add("泌尿系彩色多普勒超声检查\\[体检\\][\r\n]{1,}([\\s\\S]*?日期:[\\d-]*)");
		Patterns.add("经腹部妇科彩色多普勒超声检查\\[体检\\][\r\n]{1,}([\\s\\S]*?日期:[\\d-]*)");
		Patterns.add("十二通道常规心电图检查（体检中心\\)[\r\n]{1,}(.*)[\r\n]{1}");
		Patterns.add("骨密度测定[\r\n]{1,}(.*)[\r\n]{1}");
		Patterns.add("妇科液基薄层细胞学检查与诊断[\r\n]{1,}(.*)[\r\n]{1}");
		Patterns.add("胸部正侧位[\r\n]{1,}(.*)[\r\n]{1}");
		Patterns.add("胸部CT平扫[\r\n]{1,}(.*)[\r\n]{1}");
		Patterns.add("颅脑CT平扫[\r\n]{1,}(.*)[\r\n]{1}");
		Patterns.add("颅脑MR平扫成像+DWI成像[\r\n]{1,}(.*)[\r\n]{1}");
		Patterns.add("经颅彩色多普勒超声检查[\r\n]{1,}(.*)[\r\n]{1}");
		Patterns.add("幽门螺杆菌IgG抗体[\r\n]{1,}(.*)[\r\n]{1}");
		Patterns.add("C13呼气试验[\r\n]{1,}([\\s\\S]*?日期:[\\d-]*)");
		Patterns.add("C14呼气试验[\r\n]{1,}(.*)[\r\n]{1}");
	}
}
